services:
  db:
    image: postgres:16-alpine
    container_name: my_news_db
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password1234'
      POSTGRES_DATABASE: 'nestjs_news'
    ports:
        - '5432:5432'
    volumes:
    - postgres_data:/var/lib/postgresql/data 
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password12345
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    # สั่งให้สร้าง Image จาก Dockerfile ที่อยู่ในโฟลเดอร์ backend
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: news-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://admin:password1234@db:5432/nestjs_news?schema=public"
      
      # ตั้งค่า Secret และ Port
      JWT_SECRET: "my-super-secret-key"
      PORT: 3000
    depends_on:
      - db # รอให้ Database รันเสร็จก่อน ค่อยรัน Backend

volumes:
  postgres_data:   
