# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nestjs-backend
# spec:
#   replicas: 2 # üëà ‡πÄ‡∏£‡∏≤‡∏°‡∏µ 2 Workers ‡∏Å‡πá‡∏£‡∏±‡∏ô 2 ‡∏ï‡∏±‡∏ß‡πÑ‡∏õ‡πÄ‡∏•‡∏¢ ‡∏ä‡πà‡∏ß‡∏¢‡∏Å‡∏±‡∏ô‡∏ó‡∏≥‡∏á‡∏≤‡∏ô
#   selector:
#     matchLabels:
#       app: nestjs-backend
#   template:
#     metadata:
#       labels:
#         app: nestjs-backend
#     spec:
#       imagePullSecrets:
#         - name: ghcr-secret # üëà ‡∏ä‡∏∑‡πà‡∏≠‡∏Å‡∏∏‡∏ç‡πÅ‡∏à‡∏à‡∏≤‡∏Å‡∏Ç‡πâ‡∏≠ 1
#       containers:
#         - name: nestjs-backend
#           image: ghcr.io/aunkko-0/nestjs-news-backend:latest # üëà ‡∏ä‡∏∑‡πà‡∏≠ Image ‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 3000
#           env:
#             # üëá ‡πÅ‡∏Å‡πâ IP Database ‡πÉ‡∏´‡πâ‡πÄ‡∏õ‡πá‡∏ô IP ‡∏à‡∏£‡∏¥‡∏á‡∏Ç‡∏≠‡∏á‡πÄ‡∏Ñ‡∏£‡∏∑‡πà‡∏≠‡∏á Database
#             # ‡∏´‡πâ‡∏≤‡∏°‡πÉ‡∏ä‡πâ localhost ‡∏´‡∏£‡∏∑‡∏≠ 127.0.0.1 ‡πÄ‡∏î‡πá‡∏î‡∏Ç‡∏≤‡∏î!
#             - name: DATABASE_URL
#               value: "DATABASE_URL_PLACEHOLDER"

# ---
# # ‡∏™‡πà‡∏ß‡∏ô‡∏ó‡∏µ‡πà‡πÄ‡∏õ‡∏¥‡∏î‡∏õ‡∏£‡∏∞‡∏ï‡∏π‡πÉ‡∏´‡πâ‡∏Ñ‡∏ô‡πÄ‡∏Ç‡πâ‡∏≤‡∏°‡∏≤‡∏Ñ‡∏∏‡∏¢
# apiVersion: v1
# kind: Service
# metadata:
#   name: nestjs-backend-service
# spec:
#   selector:
#     app: nestjs-backend
#   type: NodePort # üëà ‡πÉ‡∏ä‡πâ NodePort ‡πÄ‡∏û‡∏£‡∏≤‡∏∞‡πÄ‡∏£‡∏≤‡∏ó‡∏≥ Server ‡πÄ‡∏≠‡∏á (‡∏¢‡∏±‡∏á‡πÑ‡∏°‡πà‡∏°‡∏µ LoadBalancer ‡πÅ‡∏ö‡∏ö Cloud)
#   ports:
#     - protocol: TCP
#       port: 3000       # Port ‡∏†‡∏≤‡∏¢‡πÉ‡∏ô Cluster
#       targetPort: 3000 # Port ‡∏Ç‡∏≠‡∏á Container
#       nodePort: 30001  # üëà Port ‡∏ó‡∏µ‡πà‡πÄ‡∏£‡∏≤‡∏à‡∏∞‡πÄ‡∏£‡∏µ‡∏¢‡∏Å‡∏à‡∏≤‡∏Å‡∏Ç‡πâ‡∏≤‡∏á‡∏ô‡∏≠‡∏Å (Fixed ‡πÑ‡∏ß‡πâ‡∏à‡∏∞‡πÑ‡∏î‡πâ‡∏à‡∏≥‡∏á‡πà‡∏≤‡∏¢)