# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nestjs-api
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nestjs-api
#   template:
#     metadata:
#       labels:
#         app: nestjs-api
#     spec:
#       containers:
#       - name: api
#         image: ghcr.io/aunkko-0/nestjs-news-backend:latest
#         ports:
#         - containerPort: 3000
#         env:
#         - name: DATABASE_URL
#           value: "postgresql://admin:password1234@postgres-service:5432/nestjs_news"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nestjs-api-service
# spec:
#   type: NodePort
#   selector:
#     app: nestjs-api
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 3000
#     nodePort: 30001