# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nestjs-frontend
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nestjs-frontend
#   template:
#     metadata:
#       labels:
#         app: nestjs-frontend
#     spec:
#       imagePullSecrets:
#         - name: ghcr-secret
#       containers:
#         - name: nestjs-frontend
#           image: ghcr.io/aunkko-0/nestjs-news-frontend:latest
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 80
#           env:
#             - name: NEXT_PUBLIC_API_URL
#               value: 'http://100.31.190.148:30001'
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nestjs-frontend-service
# spec:
#   selector:
#     app: nestjs-frontend
#   type: NodePort
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30002
